version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:kBRYrXFeTaeYHzwlDaKktTVCxJLhYaCL@monorail.proxy.rlwy.net:38812/thriftko
      - REDIS_URL=redis://redis:6379/0
      - MODEL_PATH=/app/service/lightfm_model.pkl
    depends_on:
      - redis
    volumes:
      - ./service:/app/service
      - ./app:/app/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
